### ISSUE TITLE
Error While Running the script

### ISSUE THREAD

**Issue by exrme18** [cyberark/kubernetes-rbac-audit#1]
Hi,

I am getting the following error while running the script. 

<img width="912" alt="Screenshot 2020-02-19 at 6 54 22 PM" src="https://user-images.githubusercontent.com/40659223/74838816-3f207b00-534a-11ea-9d0e-99ef2a960130.png">

**Comment by mike-trewartha** [comment]
I had a similar issue, ensure you're using Python3 and not 2.7

**Comment by exrme18** [comment]
I am using the python3 to run the script but still getting the same error. Would there be any workaround?

**Comment by c0d3xpl0it** [comment]
It works fine with Python 3.6.5

**Comment by o-IDA** [comment]
@exrme18 what is your python version?
Im using Python 3.7.1

**Comment by dan-leanix** [comment]
If you have Python 2 and Python 3 on your system in most cases `python` calls Python 2 and `python3` calls Python 3.

Furthermore `colorama` needs to be installed as well.

**Comment by ghost** [comment]
Hi,

With Python version 3.6.5 I'm getting following error:

Traceback (most recent call last):
  File "ExtensiveRoleCheck.py", line 203, in <module>
    extensiveClusterRolesChecker = ExtensiveRolesChecker(clusterRole_json_file, role_kind)
  File "ExtensiveRoleCheck.py", line 29, in __init__
    self._generate()
  File "ExtensiveRoleCheck.py", line 46, in _generate
    for rule in entity['rules']:
TypeError: 'NoneType' object is not iterable

**Comment by 0xz00n** [comment]
> 
> 
> Hi,
> 
> With Python version 3.6.5 I'm getting following error:
> 
> Traceback (most recent call last):
> File "ExtensiveRoleCheck.py", line 203, in
> extensiveClusterRolesChecker = ExtensiveRolesChecker(clusterRole_json_file, role_kind)
> File "ExtensiveRoleCheck.py", line 29, in **init**
> self._generate()
> File "ExtensiveRoleCheck.py", line 46, in _generate
> for rule in entity['rules']:
> TypeError: 'NoneType' object is not iterable

I've placed a pull request in with the fix for this problem.

**Comment by Hakob** [comment]
PR #6

**Comment by thecowmilk** [comment]
Could someone do a version without colorama package or do it in bash? It would be very greatful

**Comment by 0xabdi** [comment]
> Hi,
> 
> With Python version 3.6.5 I'm getting following error:
> 
> Traceback (most recent call last):
> File "ExtensiveRoleCheck.py", line 203, in
> extensiveClusterRolesChecker = ExtensiveRolesChecker(clusterRole_json_file, role_kind)
> File "ExtensiveRoleCheck.py", line 29, in **init**
> self._generate()
> File "ExtensiveRoleCheck.py", line 46, in _generate
> for rule in entity['rules']:
> TypeError: 'NoneType' object is not iterable

Facing the same issue on python 3.6.9 even after installing colorama.

**Comment by 0xabdi** [comment]
> > Hi,
> > With Python version 3.6.5 I'm getting following error:
> > Traceback (most recent call last):
> > File "ExtensiveRoleCheck.py", line 203, in
> > extensiveClusterRolesChecker = ExtensiveRolesChecker(clusterRole_json_file, role_kind)
> > File "ExtensiveRoleCheck.py", line 29, in **init**
> > self._generate()
> > File "ExtensiveRoleCheck.py", line 46, in _generate
> > for rule in entity['rules']:
> > TypeError: 'NoneType' object is not iterable
> 
> Facing the same issue on python 3.6.9 even after installing colorama.

Realized these lines in this [PR ](https://github.com/cyberark/kubernetes-rbac-audit/pull/5/commits/d933394528d6b99135a90d7b1b14104a421831cb) are not present in the python file. Added them and it is running fine now.

![image](https://user-images.githubusercontent.com/17492419/121341026-8dcb9d00-c920-11eb-841f-d02a2317dce2.png)

**Comment by holasoysoler** [comment]
I'm getting the same error 

`File "ExtensiveRoleCheck.py", line 24
    self._role_format = logging.Formatter(f'{Fore.YELLOW}[!][%(name)s]{Fore.WHITE}\u2192 %(message)s')
                                                                                                    ^
SyntaxError: invalid syntax
`

**Comment by R011y** [comment]
> > > Hi,
> > > With Python version 3.6.5 I'm getting following error:
> > > Traceback (most recent call last):
> > > File "ExtensiveRoleCheck.py", line 203, in
> > > extensiveClusterRolesChecker = ExtensiveRolesChecker(clusterRole_json_file, role_kind)
> > > File "ExtensiveRoleCheck.py", line 29, in **init**
> > > self._generate()
> > > File "ExtensiveRoleCheck.py", line 46, in _generate
> > > for rule in entity['rules']:
> > > TypeError: 'NoneType' object is not iterable
> > 
> > 
> > Facing the same issue on python 3.6.9 even after installing colorama.
> 
> Realized these lines in this [PR ](https://github.com/cyberark/kubernetes-rbac-audit/pull/5/commits/d933394528d6b99135a90d7b1b14104a421831cb) are not present in the python file. Added them and it is running fine now.
> 
> ![image](https://user-images.githubusercontent.com/17492419/121341026-8dcb9d00-c920-11eb-841f-d02a2317dce2.png)

Attempted adding this but now getting a new error:
![image](https://user-images.githubusercontent.com/92528006/217269220-23e85945-7f34-4e13-abfb-ee0d6e3e1ea8.png)
